version: '3.1'

services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=kapalma05@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASS}
    ports:
      - "5050:80"